### ISSUE TITLE
NuGet Version is from 6 months ago

### ISSUE THREAD

**Issue by nicfulton** [wieslawsoltes/PanAndZoom#16]
Hi! Thanks for the work on this - really great. I'm pleased to see the PanButton update which I would like to use but I'm generally restricted to importing packages through NuGet. I note the NuGet, v0.5.1, version is from 6 months ago. Any change to publish an update with the added features? Thanks - not sure this is technically an 'issue'. Sorry if I'm abusing this.

**Comment by wieslawsoltes** [comment]
@nicfulton Sorry for this. I am aware of this issue. The release version is coupled with version of AvaloniaUI  framework, because they do not released recently any updates I am using theirs nightly NuGet feed. Because of this I can not release on official NuGet. You can use nightly NuGet feed for PanAndZoom, see more details here https://github.com/wieslawsoltes/PanAndZoom#nuget

**Comment by nicfulton** [comment]
No need to be sorry. I totally understand. And in fact your solution of adding the alternative NuGet source will work for me. I just tried and it worked well. Thanks so much for the amazingly quick response!

**Comment by wieslawsoltes** [comment]
Will release new version today.
